### ISSUE TITLE
BaseOcrModel.post_process_cells() missing 1 required positional argument: 'conv_res' with docling 2.116.0

### ISSUE THREAD

**Issue by victcamara** [felixdittrich92/docling-OCR-OnnxTR#20]
Hi and thanks for your plugin !

I'm reporting a compatibility issue with docling 2.116.0. The same code works perfectly on docling 2.115.0. It looks like docling 2.116.0 changed the signature of BaseOcrModel.post_process_cells() to require a new conv_res argument, but the plugin still calls it with the old signature.

### Environment
- docling-ocr-onnxtr: 0.2.1
- docling: 2.116.0 (works on 2.115.0)
- OS: Windows
- Python: 3.11.9

### Reproducer
Using the sample from the README:

``` 
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import (
    ConversionResult,
    DocumentConverter,
    InputFormat,
    PdfFormatOption,
)
from docling_ocr_onnxtr import OnnxtrOcrOptions

source = "https://arxiv.org/pdf/2408.09869v4"
ocr_options = OnnxtrOcrOptions(
    # Text detection model
    det_arch="db_mobilenet_v3_large",
    # Text recognition model - from Hugging Face Hub
    reco_arch="Felix92/onnxtr-parseq-multilingual-v1",
    # This can be set to `True` to auto-correct the orientation of the pages
    auto_correct_orientation=False,
)

pipeline_options = PdfPipelineOptions(
    ocr_options=ocr_options,
)
pipeline_options.allow_external_plugins = True  # <-- enabled the external plugins

# Convert the document
converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options,
        ),
    },
)

conversion_result: ConversionResult = converter.convert(source=source)
doc = conversion_result.document
md = doc.export_to_markdown()
print(md)

```

### Error

`
ERROR docling.pipeline.standard_pdf_pipeline:standard_pdf_pipeline.py:380 Stage ocr failed for run 1: BaseOcrModel.post_process_cells() missing 1 required positional argument: 'conv_res'
Traceback (most recent call last):
  File ".../docling/pipeline/standard_pdf_pipeline.py", line 355, in _process_batch
    processed_pages = list(self.model(good[0].conv_res, pages))
  File ".../docling_ocr_onnxtr/onnxtr_model.py", line 200, in __call__
    self.post_process_cells(all_ocr_cells, page)
TypeError: BaseOcrModel.post_process_cells() missing 1 required positional argument: 'conv_res'
`

### Root cause
In docling 2.116.0, BaseOcrModel.post_process_cells() now requires conv_res as the 3rd positional argument:

_docling/models/base_ocr_model.py:211_
`def post_process_cells(self, ocr_cells, page, conv_res, priority=None) -> None:`

But `OnnxtrOcrModel.__call__` still uses the old 2-argument call at onnxtr_model.py:200:
`self.post_process_cells(all_ocr_cells, page)`

Thank you !

**Comment by webbrain-one** [comment]
Hi, thanks for the detailed report! I opened a pull request, #21, that fixes this compatibility issue with docling 2.116.0 by passing the required `conv_res` argument to `post_process_cells()` in `OnnxtrOcrModel.__call__`.

PR: https://github.com/felixdittrich92/docling-OCR-OnnxTR/pull/21
